name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install NPM
        run: npm install
      - name: Build and test
        working-directory: ./projects/object-validator
        run: npm run build --if-present
      - name: Test with coverage
        working-directory: ./projects/object-validator
        run: npm run test:no-watch
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
